### ISSUE TITLE
Any way to integrate this plugin with a NodeJS API?

### ISSUE THREAD

**Issue by meghead** [BlupGithub/social_login_3#2]
I'm using the Social Login plugin to retrieve the username and avatar from FB, Google or Twitter and store that info both internally to Hive in Flutter and an external Mysql database. But now I've decided to go headless with a NodeJS API and authentication. Is there a way to integrate this with the Social Login plugin?

**Comment by SahajRana** [comment]
Hi @meghead, what do you mean by going headless with a NodeJS API. My approach would be to use this plugin to get the login credentials after successful login and then pass it to nodeJS API. Am I missing something?

**Comment by meghead** [comment]
Yes. That seems the right approach. Thanks!
